/*BEGIN_FILE_HDR
********************************************************************
* NOTICE
* This software is the property of XiangBin Electric. Any information
* contained in this doc should not be reproduced, or used, or
*disclosed without the written authorization from XiangBin Electric.
********************************************************************
* File Name:Common.c
********************************************************************
* Project/Product:t3622
* Title:
* Author:yhd
*********************************************************************
* Description:
* 1.Define common used functions
*
* (Requirements, pseudo code and etc.)
*********************************************************************
* Limitations:
*
* (limitations)
*********************************************************************
*********************************************************************
* Revision History：
*
* Version       Date         	  Author       Descriptions
* ----------    --------------  ------------   ------------
* 1.0           2021-08-17      yhd            Original
*
*
********************************************************************
*END_FILE_HDR*/

/* Includes*/
/******************************************************************/
#include "Common.h"

/* Variables */
/******************************************************************/
static const u16 CrcCcittTab[256] = {
  0x0000, 0x1021, 0x2042, 0x3063, 0x4084, 0x50a5, 0x60c6, 0x70e7, 0x8108, 0x9129, 0xa14a, 0xb16b, 0xc18c, 0xd1ad,
  0xe1ce, 0xf1ef, 0x1231, 0x0210, 0x3273, 0x2252, 0x52b5, 0x4294, 0x72f7, 0x62d6, 0x9339, 0x8318, 0xb37b, 0xa35a,
  0xd3bd, 0xc39c, 0xf3ff, 0xe3de, 0x2462, 0x3443, 0x0420, 0x1401, 0x64e6, 0x74c7, 0x44a4, 0x5485, 0xa56a, 0xb54b,
  0x8528, 0x9509, 0xe5ee, 0xf5cf, 0xc5ac, 0xd58d, 0x3653, 0x2672, 0x1611, 0x0630, 0x76d7, 0x66f6, 0x5695, 0x46b4,
  0xb75b, 0xa77a, 0x9719, 0x8738, 0xf7df, 0xe7fe, 0xd79d, 0xc7bc, 0x48c4, 0x58e5, 0x6886, 0x78a7, 0x0840, 0x1861,
  0x2802, 0x3823, 0xc9cc, 0xd9ed, 0xe98e, 0xf9af, 0x8948, 0x9969, 0xa90a, 0xb92b, 0x5af5, 0x4ad4, 0x7ab7, 0x6a96,
  0x1a71, 0x0a50, 0x3a33, 0x2a12, 0xdbfd, 0xcbdc, 0xfbbf, 0xeb9e, 0x9b79, 0x8b58, 0xbb3b, 0xab1a, 0x6ca6, 0x7c87,
  0x4ce4, 0x5cc5, 0x2c22, 0x3c03, 0x0c60, 0x1c41, 0xedae, 0xfd8f, 0xcdec, 0xddcd, 0xad2a, 0xbd0b, 0x8d68, 0x9d49,
  0x7e97, 0x6eb6, 0x5ed5, 0x4ef4, 0x3e13, 0x2e32, 0x1e51, 0x0e70, 0xff9f, 0xefbe, 0xdfdd, 0xcffc, 0xbf1b, 0xaf3a,
  0x9f59, 0x8f78, 0x9188, 0x81a9, 0xb1ca, 0xa1eb, 0xd10c, 0xc12d, 0xf14e, 0xe16f, 0x1080, 0x00a1, 0x30c2, 0x20e3,
  0x5004, 0x4025, 0x7046, 0x6067, 0x83b9, 0x9398, 0xa3fb, 0xb3da, 0xc33d, 0xd31c, 0xe37f, 0xf35e, 0x02b1, 0x1290,
  0x22f3, 0x32d2, 0x4235, 0x5214, 0x6277, 0x7256, 0xb5ea, 0xa5cb, 0x95a8, 0x8589, 0xf56e, 0xe54f, 0xd52c, 0xc50d,
  0x34e2, 0x24c3, 0x14a0, 0x0481, 0x7466, 0x6447, 0x5424, 0x4405, 0xa7db, 0xb7fa, 0x8799, 0x97b8, 0xe75f, 0xf77e,
  0xc71d, 0xd73c, 0x26d3, 0x36f2, 0x0691, 0x16b0, 0x6657, 0x7676, 0x4615, 0x5634, 0xd94c, 0xc96d, 0xf90e, 0xe92f,
  0x99c8, 0x89e9, 0xb98a, 0xa9ab, 0x5844, 0x4865, 0x7806, 0x6827, 0x18c0, 0x08e1, 0x3882, 0x28a3, 0xcb7d, 0xdb5c,
  0xeb3f, 0xfb1e, 0x8bf9, 0x9bd8, 0xabbb, 0xbb9a, 0x4a75, 0x5a54, 0x6a37, 0x7a16, 0x0af1, 0x1ad0, 0x2ab3, 0x3a92,
  0xfd2e, 0xed0f, 0xdd6c, 0xcd4d, 0xbdaa, 0xad8b, 0x9de8, 0x8dc9, 0x7c26, 0x6c07, 0x5c64, 0x4c45, 0x3ca2, 0x2c83,
  0x1ce0, 0x0cc1, 0xef1f, 0xff3e, 0xcf5d, 0xdf7c, 0xaf9b, 0xbfba, 0x8fd9, 0x9ff8, 0x6e17, 0x7e36, 0x4e55, 0x5e74,
  0x2e93, 0x3eb2, 0x0ed1, 0x1ef0};

/* BEGIN_FUNCTION_HDR
********************************************************************
* Function Name: Common_exeLookUpTable
* Description:
*   This lookup table function is generated by simlink.
*
* Inputs:
* 1.u0       :x
* 2.bp0[]    :x table
* 3.table[]  :y table
* 4.maxIndex :max index of table and bp0
*
* Outputs:
* 1.y
*
* Limitations:
********************************************************************
END_FUNCTION_HDR*/
s16 Common_exeLookUpTable(s16 u0, const s16 bp0[], const s16 table[], s32 maxIndex)
{
  u32 frac;
  s16 y_0;
  s32 bpIdx;

  /* Lookup 1-D
     Search method: 'linear'
     Use previous index: 'off'
     Interpolation method: 'Linear'
     Use last breakpoint for index at or above upper limit: 'on'
     Remove protection against out-of-range input in generated code:
     'on' Rounding mode: 'simplest'
   */
  /* Prelookup - Index and Fraction
     Index Search method: 'linear'
     Use previous index: 'off'
     Use last breakpoint for index at or above upper limit: 'on'
     Remove protection against out-of-range input in generated code:
     'on' Rounding mode: 'simplest'
   */
  /* Linear Search */
  /* polyspace +1 MISRA-C3:10.1 */
  bpIdx = maxIndex >> 1U;

  if (u0 < bp0[0])
  {
    return table[0];
  }

  while ((u0 < bp0[bpIdx]) && (bpIdx > 0U))
  {
    bpIdx--;
  }

  while ((bpIdx < maxIndex) && (u0 >= bp0[bpIdx + 1U]))
  {
    bpIdx++;
  }

  /* polyspace-begin MISRA-C3:10.1,10.8 */
  frac = (u32)(((s32)(u16)((s32)u0 - bp0[bpIdx]) << 10) / (u16)(bp0[bpIdx + 1U] - bp0[bpIdx]));
  /* polyspace-EndAddr MISRA-C3:10.1,10.8 */

  /* Interpolation 1-D
     Interpolation method: 'Linear'
     Use last breakpoint for index at or above upper limit: 'on'
     Rounding mode: 'simplest'
     Overflow mode: 'wrapping'
   */

  if (bpIdx == maxIndex)
  {
    y_0 = table[bpIdx];
  }
  else
  {
    /* polyspace-begin MISRA-C3:10.8 */

    y_0 = (s16)((s16)(((table[bpIdx + 1U] - table[bpIdx]) * frac) >> 10) + table[bpIdx]);
    /* polyspace-EndAddr MISRA-C3:10.8 */
  }

  return y_0;
}
/* BEGIN_FUNCTION_HDR
********************************************************************
* Function Name:Common_cpMemory
* Description:
*   Implament copy memory function.
*
* Inputs:
* 1.des :destination address
* 2.src :source address
* 3.length:length of data to copy in byte
*
* Outputs:
*
*
* Limitations:
********************************************************************
END_FUNCTION_HDR*/
void Common_cpMemory(u8 des[], u8 src[], u8 length)
{
  u8 i;
  for (i = 0u; i < length; i++)
  {
    des[i] = src[i];
  }
}
/* BEGIN_FUNCTION_HDR
********************************************************************
* Function Name:Common_setStatusDelay
* Description:
*   Filter a status in time domain
*
* Inputs:
* 1.status : false or true
* 2.filtertime: filtertime for status to settle
* 3.currenttime:currenttime for status, must not modified this
varible
* externally.
*
* Outputs:
* 1.filtered status
*
*
* Limitations:
********************************************************************
END_FUNCTION_HDR*/
u8 Common_setStatusDelay(u8 status, u16 filtertime, u16 *currenttime)
{
  u8 ret = 0u;
  if (status != 0u)
  {
    if ((*currenttime) < filtertime)
    {
      (*currenttime) = (*currenttime)++;
    }
    else
    {
      ret = 1u;
    }
  }
  else
  {
    (*currenttime) = 0u;
  }

  return ret;
}
/* BEGIN_FUNCTION_HDR
********************************************************************
* Function Name:Common_calcCrc16Ccitt
* Description:
*
*
* Inputs:
*
*
* Outputs:
*
*
* Limitations:
********************************************************************
END_FUNCTION_HDR*/
u16 Common_calcCrc16Ccitt(const u8 *BeginAddr, const u8 *EndAddr)
{
  u16 Crc = 0xFFFFu;
  u16 Tmp = 0u;

  for (; BeginAddr < EndAddr; BeginAddr++)
  {
    Tmp = (*BeginAddr ^ (Crc >> 8)) & 0xFFu;
    /* polyspace +1 DEFECT:UINT_CONV_OVFL */
    Crc = CrcCcittTab[Tmp] ^ (Crc << 8);
  }
  return (Crc);
}
